package tela.condomino;

import dao.CondominoDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Condomino;
import modelo.TipoUsuario;

public class CondominoDetalhesTela extends javax.swing.JFrame {

    public Condomino condomino;
    
    /**
     * Creates new form CadastraCondomino
     */
    public CondominoDetalhesTela() {
    }
    
    public CondominoDetalhesTela(Condomino condomino) {
        initComponents();
        this.condomino = condomino;
        listaTelefone.setModel(new DefaultListModel());
        dadosCondomino();
    }

    // transforma Calendar em String
    private String dataFormatada(Calendar data){
        Calendar c = data;
        Date date = c.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        return sdf.format(date);
    }

    private void dadosCondomino() {
        labelNome.setText(this.condomino.getNome());
        labelCpf.setText(this.condomino.getCpf());
        labelDataNascimento.setText(dataFormatada(this.condomino.getDataNascimento()));
        labelEstadoCivil.setText(this.condomino.getEstadoCivil().getDescricao());
        
        for(String telefone : this.condomino.getTelefones())
            ((DefaultListModel)(listaTelefone.getModel()))
               .addElement(telefone);
        
        labelLogin.setText(this.condomino.getLogin());
        labelSenha.setText(this.condomino.getSenha());
        labelBloco.setText("" + this.condomino.getApartamento().getBloco());
        labelAndar.setText("" + this.condomino.getApartamento().getAndar());
        labelNumero.setText(this.condomino.getApartamento().getNumApartamento());
        
        if (this.condomino.getTipoUsuario() == TipoUsuario.ADMIN) {
            labelPerfil.setText("Administrador");
        } else {
            labelPerfil.setText("Condômino");
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDados = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        lCpf = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        lDataNascimento = new javax.swing.JLabel();
        labelDataNascimento = new javax.swing.JLabel();
        lEstadoCivil = new javax.swing.JLabel();
        labelEstadoCivil = new javax.swing.JLabel();
        painelTelefones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTelefone = new javax.swing.JList();
        painelAcessoLocalizacao = new javax.swing.JPanel();
        painelAcesso = new javax.swing.JPanel();
        lLogin = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        lApartamento1 = new javax.swing.JLabel();
        labelPerfil = new javax.swing.JLabel();
        painelApartamento = new javax.swing.JPanel();
        lBloco = new javax.swing.JLabel();
        labelBloco = new javax.swing.JLabel();
        lAndar = new javax.swing.JLabel();
        labelAndar = new javax.swing.JLabel();
        lNumero = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botaoAlterar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Condômino");

        painelDados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        lNome.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lNome.setText("Nome:");

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelNome.setText("jLabel1");

        lCpf.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lCpf.setText("CPF:");

        labelCpf.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelCpf.setText("jLabel1");

        lDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lDataNascimento.setText("Data de nascimento:");

        labelDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelDataNascimento.setText("jLabel1");

        lEstadoCivil.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lEstadoCivil.setText("Estado Civil:");

        labelEstadoCivil.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelEstadoCivil.setText("jLabel1");

        painelTelefones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Telefones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        listaTelefone.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaTelefone);

        javax.swing.GroupLayout painelTelefonesLayout = new javax.swing.GroupLayout(painelTelefones);
        painelTelefones.setLayout(painelTelefonesLayout);
        painelTelefonesLayout.setHorizontalGroup(
            painelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelefonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelTelefonesLayout.setVerticalGroup(
            painelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addComponent(lNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDataNascimento)
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNome)
                                    .addComponent(labelDataNascimento))
                                .addGap(206, 206, 206)
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lCpf)
                                    .addComponent(lEstadoCivil)
                                    .addGroup(painelDadosLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelEstadoCivil)
                                            .addComponent(labelCpf))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(lCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(labelCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDataNascimento)
                    .addComponent(lEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNascimento)
                    .addComponent(labelEstadoCivil))
                .addGap(18, 18, 18)
                .addComponent(painelTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelAcessoLocalizacao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados de Localização e Acesso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        painelAcesso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Acesso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        lLogin.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lLogin.setText("Login:");

        labelLogin.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelLogin.setText("jLabel1");

        lSenha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lSenha.setText("Senha:");

        labelSenha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelSenha.setText("jLabel1");

        lApartamento1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lApartamento1.setText("Perfil:");

        labelPerfil.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelPerfil.setText("jLabel1");

        javax.swing.GroupLayout painelAcessoLayout = new javax.swing.GroupLayout(painelAcesso);
        painelAcesso.setLayout(painelAcessoLayout);
        painelAcessoLayout.setHorizontalGroup(
            painelAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAcessoLayout.createSequentialGroup()
                .addGroup(painelAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAcessoLayout.createSequentialGroup()
                        .addComponent(lLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLogin))
                    .addGroup(painelAcessoLayout.createSequentialGroup()
                        .addComponent(lSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSenha))
                    .addGroup(painelAcessoLayout.createSequentialGroup()
                        .addComponent(lApartamento1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPerfil)))
                .addGap(0, 127, Short.MAX_VALUE))
        );
        painelAcessoLayout.setVerticalGroup(
            painelAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAcessoLayout.createSequentialGroup()
                .addGroup(painelAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLogin)
                    .addComponent(labelLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSenha)
                    .addComponent(labelSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lApartamento1)
                    .addComponent(labelPerfil))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        painelApartamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Apartamento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        lBloco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lBloco.setText("Bloco:");

        labelBloco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBloco.setText("jLabel3");

        lAndar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lAndar.setText("Andar:");

        labelAndar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAndar.setText("jLabel5");

        lNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lNumero.setText("Número:");

        labelNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNumero.setText("jLabel7");

        javax.swing.GroupLayout painelApartamentoLayout = new javax.swing.GroupLayout(painelApartamento);
        painelApartamento.setLayout(painelApartamentoLayout);
        painelApartamentoLayout.setHorizontalGroup(
            painelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelApartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelApartamentoLayout.createSequentialGroup()
                        .addComponent(lBloco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelBloco))
                    .addGroup(painelApartamentoLayout.createSequentialGroup()
                        .addComponent(lAndar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelAndar))
                    .addGroup(painelApartamentoLayout.createSequentialGroup()
                        .addComponent(lNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNumero)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelApartamentoLayout.setVerticalGroup(
            painelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelApartamentoLayout.createSequentialGroup()
                .addGroup(painelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBloco)
                    .addComponent(labelBloco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAndar)
                    .addComponent(labelAndar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumero)
                    .addComponent(labelNumero))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelAcessoLocalizacaoLayout = new javax.swing.GroupLayout(painelAcessoLocalizacao);
        painelAcessoLocalizacao.setLayout(painelAcessoLocalizacaoLayout);
        painelAcessoLocalizacaoLayout.setHorizontalGroup(
            painelAcessoLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAcessoLocalizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelApartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelAcessoLocalizacaoLayout.setVerticalGroup(
            painelAcessoLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAcessoLocalizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAcessoLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelApartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(painelAcessoLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAcessoLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        CondominoAtualizarTela alterar;
        try {
            alterar = new CondominoAtualizarTela(this.condomino);
            alterar.setVisible(true);
        } catch (ParseException ex) {
            ex.getMessage();
        }
        
        dispose();
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o condômino: "+this.condomino.getNome()+"?", "Aviso", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION){
            CondominoDAO dao = new CondominoDAO();
            dao.excluiCondomino(this.condomino);
            JOptionPane.showMessageDialog(this, "Condômino excluído com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
        
        
        
    }//GEN-LAST:event_botaoExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CondominoDetalhesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CondominoDetalhesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CondominoDetalhesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CondominoDetalhesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CondominoDetalhesTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lAndar;
    private javax.swing.JLabel lApartamento1;
    private javax.swing.JLabel lBloco;
    private javax.swing.JLabel lCpf;
    private javax.swing.JLabel lDataNascimento;
    private javax.swing.JLabel lEstadoCivil;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel labelAndar;
    private javax.swing.JLabel labelBloco;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelEstadoCivil;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelPerfil;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JList listaTelefone;
    private javax.swing.JPanel painelAcesso;
    private javax.swing.JPanel painelAcessoLocalizacao;
    private javax.swing.JPanel painelApartamento;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelTelefones;
    // End of variables declaration//GEN-END:variables
}
