package tela.apartamento;

import dao.ApartamentoDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import modelo.Apartamento;
import modelo.tabela.TabelaModeloApartamento;

public class ApartamentoPesquisarTela extends javax.swing.JFrame {
    
    private List<Apartamento> aptos;
    private Apartamento apto;

    /**
     * Creates new form AdiministradorCadastroTela
     */
    public ApartamentoPesquisarTela() {
        initComponents();
        preencherLista();
        preencherTabela();
        preencherMenuFlutuante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmFlutuante = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfApartamento = new javax.swing.JTextField();
        bPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbApartamento = new javax.swing.JTable();
        bCadastrar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Apartamento");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setText("Apartamento");

        bPesquisar.setText("Pesquisar");
        bPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bPesquisar)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPesquisar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tbApartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbApartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbApartamentoMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbApartamento);

        bCadastrar.setText("Cadastrar");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bCadastrar)
                                .addGap(229, 229, 229)
                                .addComponent(bCancelar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCadastrar)
                    .addComponent(bCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        preencherLista();
        preencherTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tbApartamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbApartamentoMouseReleased
        selecionarCidade(evt);
        realizarAcao(evt);
    }//GEN-LAST:event_tbApartamentoMouseReleased

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
        ApartamentoCadastrarTela aptoCadastrar = new ApartamentoCadastrarTela();
        aptoCadastrar.setVisible(true);
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void bPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisarActionPerformed
        JOptionPane.showMessageDialog(null, "Sem função");
    }//GEN-LAST:event_bPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApartamentoPesquisarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApartamentoPesquisarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApartamentoPesquisarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApartamentoPesquisarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApartamentoPesquisarTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu pmFlutuante;
    private javax.swing.JTable tbApartamento;
    private javax.swing.JTextField tfApartamento;
    // End of variables declaration//GEN-END:variables

    private void preencherLista() {
        ApartamentoDAO dao =  new ApartamentoDAO();
        aptos = dao.listar();
    }

    private void preencherTabela() {
        tbApartamento.setModel(new TabelaModeloApartamento(aptos));
    }
    
    private void selecionarCidade(MouseEvent evt) {

        // selecionar a linha, pois, se for botão direito do mouse,não seleciona automaticamente.
        int linha =tbApartamento.rowAtPoint(evt.getPoint());

        if (linha >= 0) {

            tbApartamento.setRowSelectionInterval(linha, linha);

            linha = tbApartamento.getSelectedRow();

            this.apto = aptos.get(linha);
        }

    }

    private void realizarAcao(MouseEvent evt) {

        if (evt.getButton() == MouseEvent.BUTTON1) { // Botão Esquerdo do Mouse

            if (evt.getClickCount() > 1) { // Se for mais de 2 cliques
                verDetalhes();
            }

        } else if (evt.getButton() == MouseEvent.BUTTON3) { //Botão Direito do Mouse

            pmFlutuante.show(evt.getComponent(), evt.getX(), evt.getY());

        }

    }
    
    private void preencherMenuFlutuante() {
        
        JMenuItem itens[] = {new JMenuItem("Ver Detalhes"), new JMenuItem("Atualizar"), new JMenuItem("Remover")};
        
        itens[0].addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                verDetalhes();
            }
        }); 
        
        itens[1].addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                atualizar();
            }

        });
        
        itens[2].addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                remover();
            }

        });
        
        for (JMenuItem item : itens) {
            pmFlutuante.add(item);
        }
        
    }
    
    public void verDetalhes(){
        ApartamentoDetalhesTela aptoDetalhes =  new ApartamentoDetalhesTela(apto);
        aptoDetalhes.setVisible(true);
    }
    
    public void atualizar(){
        ApartamentoAtualizarTela aptoAtualizar =  new ApartamentoAtualizarTela(apto);
        aptoAtualizar.setVisible(true);
    }
    
    public void remover(){
        
        int res = JOptionPane.showConfirmDialog(null, "Confimar exclusão?");
        
        if(res == JOptionPane.YES_OPTION){
            
            ApartamentoDAO dao = new ApartamentoDAO();
            dao.remove(apto);
            JOptionPane.showMessageDialog(null, apto.toString() + " Excluido");
            
        } 
        
    }
    
}
